/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AppRetrospectiveRouteImport } from './routes/_app.retrospective'
import { Route as AppProposeRouteImport } from './routes/_app.propose'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppPeopleRouteImport } from './routes/_app.people'
import { Route as AppPantryRouteImport } from './routes/_app.pantry'
import { Route as AppLogRouteImport } from './routes/_app.log'
import { Route as AppGroceryRouteImport } from './routes/_app.grocery'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppRecipeSlugRouteImport } from './routes/_app.recipe.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRetrospectiveRoute = AppRetrospectiveRouteImport.update({
  id: '/retrospective',
  path: '/retrospective',
  getParentRoute: () => AppRoute,
} as any)
const AppProposeRoute = AppProposeRouteImport.update({
  id: '/propose',
  path: '/propose',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppLogRoute = AppLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppRoute,
} as any)
const AppGroceryRoute = AppGroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipeSlugRoute = AppRecipeSlugRouteImport.update({
  id: '/recipe/$slug',
  path: '/recipe/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/favorites': typeof AppFavoritesRoute
  '/grocery': typeof AppGroceryRoute
  '/log': typeof AppLogRoute
  '/pantry': typeof AppPantryRoute
  '/people': typeof AppPeopleRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/propose': typeof AppProposeRoute
  '/retrospective': typeof AppRetrospectiveRoute
  '/join/$token': typeof JoinTokenRoute
  '/recipe/$slug': typeof AppRecipeSlugRoute
}
export interface FileRoutesByTo {
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/favorites': typeof AppFavoritesRoute
  '/grocery': typeof AppGroceryRoute
  '/log': typeof AppLogRoute
  '/pantry': typeof AppPantryRoute
  '/people': typeof AppPeopleRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/propose': typeof AppProposeRoute
  '/retrospective': typeof AppRetrospectiveRoute
  '/join/$token': typeof JoinTokenRoute
  '/': typeof AppIndexRoute
  '/recipe/$slug': typeof AppRecipeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/grocery': typeof AppGroceryRoute
  '/_app/log': typeof AppLogRoute
  '/_app/pantry': typeof AppPantryRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/propose': typeof AppProposeRoute
  '/_app/retrospective': typeof AppRetrospectiveRoute
  '/join/$token': typeof JoinTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/recipe/$slug': typeof AppRecipeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/login'
    | '/signup'
    | '/favorites'
    | '/grocery'
    | '/log'
    | '/pantry'
    | '/people'
    | '/plan'
    | '/profile'
    | '/propose'
    | '/retrospective'
    | '/join/$token'
    | '/recipe/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/login'
    | '/signup'
    | '/favorites'
    | '/grocery'
    | '/log'
    | '/pantry'
    | '/people'
    | '/plan'
    | '/profile'
    | '/propose'
    | '/retrospective'
    | '/join/$token'
    | '/'
    | '/recipe/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/connect'
    | '/login'
    | '/signup'
    | '/_app/favorites'
    | '/_app/grocery'
    | '/_app/log'
    | '/_app/pantry'
    | '/_app/people'
    | '/_app/plan'
    | '/_app/profile'
    | '/_app/propose'
    | '/_app/retrospective'
    | '/join/$token'
    | '/_app/'
    | '/_app/recipe/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/retrospective': {
      id: '/_app/retrospective'
      path: '/retrospective'
      fullPath: '/retrospective'
      preLoaderRoute: typeof AppRetrospectiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/propose': {
      id: '/_app/propose'
      path: '/propose'
      fullPath: '/propose'
      preLoaderRoute: typeof AppProposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry': {
      id: '/_app/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log': {
      id: '/_app/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AppLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grocery': {
      id: '/_app/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof AppGroceryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipe/$slug': {
      id: '/_app/recipe/$slug'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug'
      preLoaderRoute: typeof AppRecipeSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppGroceryRoute: typeof AppGroceryRoute
  AppLogRoute: typeof AppLogRoute
  AppPantryRoute: typeof AppPantryRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProposeRoute: typeof AppProposeRoute
  AppRetrospectiveRoute: typeof AppRetrospectiveRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRecipeSlugRoute: typeof AppRecipeSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFavoritesRoute: AppFavoritesRoute,
  AppGroceryRoute: AppGroceryRoute,
  AppLogRoute: AppLogRoute,
  AppPantryRoute: AppPantryRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppPlanRoute: AppPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppProposeRoute: AppProposeRoute,
  AppRetrospectiveRoute: AppRetrospectiveRoute,
  AppIndexRoute: AppIndexRoute,
  AppRecipeSlugRoute: AppRecipeSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ConnectRoute: ConnectRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
