#!/bin/bash
# SessionStart hook for Claude Code on the web.
#
# The repo's local toolchain is bootstrapped via mise (.devcontainer + mise.toml),
# but the web remote environment does not build the devcontainer or run its
# postCreateCommand, so node_modules is never populated. The environment setup
# script installs mise + aube globally; this hook trusts the repo's mise.toml and
# restores node_modules so the openspec CLI, the Worker, and the build tooling are
# runnable before the session begins. It also exposes those CLIs as bare commands
# (see the wrapper-shim block below), since the agent's non-interactive shell never
# activates mise on its own.
set -euo pipefail

# Only needed in the remote (web) environment; local devcontainers handle setup
# via mise's postCreateCommand.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

export PATH="$HOME/.local/bin:$PATH"

cd "$CLAUDE_PROJECT_DIR"

# Trust this repo's mise.toml and install its pinned toolchain (node + aube).
mise trust
mise install

# Idempotent: `aube install` is a no-op when node_modules is already in sync, and is
# preferred over `aube ci` so the cached container state speeds up later sessions.
# `mise exec` runs it under the repo-pinned toolchain without relying on shell init.
mise exec -- aube install

# Expose the repo's CLIs as bare commands. mise.toml activates the toolchain (its
# tools + the `_.path` -> node_modules/.bin entries) only in an *interactive* shell,
# via `mise activate` in ~/.bashrc. Claude's Bash tool runs a non-interactive,
# non-login shell (`bash -c`) that sources neither ~/.bashrc nor ~/.profile, so mise
# never activates and `openspec`, `aubr`, `wrangler`, etc. are not on PATH — even
# though they're installed. The docs (CLAUDE.md, CONTRIBUTING.md) invoke them as bare
# commands, so generate thin wrappers in ~/.local/bin (already on PATH) that re-enter
# the repo toolchain via `mise exec`, pinned to the repo root so config discovery and
# trust resolve regardless of the caller's cwd.
mkdir -p "$HOME/.local/bin"
for cmd in aube aubr aubx openspec wrangler vitest; do
  cat > "$HOME/.local/bin/$cmd" <<EOF
#!/bin/sh
# Auto-generated by .claude/hooks/session-start.sh — re-enter the repo toolchain.
cd "$CLAUDE_PROJECT_DIR" && exec mise exec -- $cmd "\$@"
EOF
  chmod +x "$HOME/.local/bin/$cmd"
done
