/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as NormalizeRouteImport } from './routes/normalize'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as DiscoveryIndexRouteImport } from './routes/discovery.index'
import { Route as DataIndexRouteImport } from './routes/data.index'
import { Route as ConfigIndexRouteImport } from './routes/config.index'
import { Route as DiscoverySatellitesRouteImport } from './routes/discovery.satellites'
import { Route as DataGuidanceRouteImport } from './routes/data.guidance'
import { Route as ConfigRankingRouteImport } from './routes/config.ranking'
import { Route as ConfigIngestKeysRouteImport } from './routes/config.ingest-keys'
import { Route as ConfigFlyerRouteImport } from './routes/config.flyer'
import { Route as MembersIdIndexRouteImport } from './routes/members.$id.index'
import { Route as DataStoresIndexRouteImport } from './routes/data.stores.index'
import { Route as DataRecipesIndexRouteImport } from './routes/data.recipes.index'
import { Route as MembersIdSectionRouteImport } from './routes/members.$id.$section'
import { Route as DataStoresSlugRouteImport } from './routes/data.stores.$slug'
import { Route as DataRecipesSlugRouteImport } from './routes/data.recipes.$slug'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const NormalizeRoute = NormalizeRouteImport.update({
  id: '/normalize',
  path: '/normalize',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryIndexRoute = DiscoveryIndexRouteImport.update({
  id: '/discovery/',
  path: '/discovery/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverySatellitesRoute = DiscoverySatellitesRouteImport.update({
  id: '/discovery/satellites',
  path: '/discovery/satellites',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGuidanceRoute = DataGuidanceRouteImport.update({
  id: '/data/guidance',
  path: '/data/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRankingRoute = ConfigRankingRouteImport.update({
  id: '/config/ranking',
  path: '/config/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIngestKeysRoute = ConfigIngestKeysRouteImport.update({
  id: '/config/ingest-keys',
  path: '/config/ingest-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigFlyerRoute = ConfigFlyerRouteImport.update({
  id: '/config/flyer',
  path: '/config/flyer',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdIndexRoute = MembersIdIndexRouteImport.update({
  id: '/members/$id/',
  path: '/members/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStoresIndexRoute = DataStoresIndexRouteImport.update({
  id: '/data/stores/',
  path: '/data/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRecipesIndexRoute = DataRecipesIndexRouteImport.update({
  id: '/data/recipes/',
  path: '/data/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdSectionRoute = MembersIdSectionRouteImport.update({
  id: '/members/$id/$section',
  path: '/members/$id/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const DataStoresSlugRoute = DataStoresSlugRouteImport.update({
  id: '/data/stores/$slug',
  path: '/data/stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRecipesSlugRoute = DataRecipesSlugRouteImport.update({
  id: '/data/recipes/$slug',
  path: '/data/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/logs': typeof LogsRoute
  '/normalize': typeof NormalizeRoute
  '/usage': typeof UsageRoute
  '/config/flyer': typeof ConfigFlyerRoute
  '/config/ingest-keys': typeof ConfigIngestKeysRoute
  '/config/ranking': typeof ConfigRankingRoute
  '/data/guidance': typeof DataGuidanceRoute
  '/discovery/satellites': typeof DiscoverySatellitesRoute
  '/config/': typeof ConfigIndexRoute
  '/data/': typeof DataIndexRoute
  '/discovery/': typeof DiscoveryIndexRoute
  '/members/': typeof MembersIndexRoute
  '/data/recipes/$slug': typeof DataRecipesSlugRoute
  '/data/stores/$slug': typeof DataStoresSlugRoute
  '/members/$id/$section': typeof MembersIdSectionRoute
  '/data/recipes/': typeof DataRecipesIndexRoute
  '/data/stores/': typeof DataStoresIndexRoute
  '/members/$id/': typeof MembersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/logs': typeof LogsRoute
  '/normalize': typeof NormalizeRoute
  '/usage': typeof UsageRoute
  '/config/flyer': typeof ConfigFlyerRoute
  '/config/ingest-keys': typeof ConfigIngestKeysRoute
  '/config/ranking': typeof ConfigRankingRoute
  '/data/guidance': typeof DataGuidanceRoute
  '/discovery/satellites': typeof DiscoverySatellitesRoute
  '/config': typeof ConfigIndexRoute
  '/data': typeof DataIndexRoute
  '/discovery': typeof DiscoveryIndexRoute
  '/members': typeof MembersIndexRoute
  '/data/recipes/$slug': typeof DataRecipesSlugRoute
  '/data/stores/$slug': typeof DataStoresSlugRoute
  '/members/$id/$section': typeof MembersIdSectionRoute
  '/data/recipes': typeof DataRecipesIndexRoute
  '/data/stores': typeof DataStoresIndexRoute
  '/members/$id': typeof MembersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/logs': typeof LogsRoute
  '/normalize': typeof NormalizeRoute
  '/usage': typeof UsageRoute
  '/config/flyer': typeof ConfigFlyerRoute
  '/config/ingest-keys': typeof ConfigIngestKeysRoute
  '/config/ranking': typeof ConfigRankingRoute
  '/data/guidance': typeof DataGuidanceRoute
  '/discovery/satellites': typeof DiscoverySatellitesRoute
  '/config/': typeof ConfigIndexRoute
  '/data/': typeof DataIndexRoute
  '/discovery/': typeof DiscoveryIndexRoute
  '/members/': typeof MembersIndexRoute
  '/data/recipes/$slug': typeof DataRecipesSlugRoute
  '/data/stores/$slug': typeof DataStoresSlugRoute
  '/members/$id/$section': typeof MembersIdSectionRoute
  '/data/recipes/': typeof DataRecipesIndexRoute
  '/data/stores/': typeof DataStoresIndexRoute
  '/members/$id/': typeof MembersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/logs'
    | '/normalize'
    | '/usage'
    | '/config/flyer'
    | '/config/ingest-keys'
    | '/config/ranking'
    | '/data/guidance'
    | '/discovery/satellites'
    | '/config/'
    | '/data/'
    | '/discovery/'
    | '/members/'
    | '/data/recipes/$slug'
    | '/data/stores/$slug'
    | '/members/$id/$section'
    | '/data/recipes/'
    | '/data/stores/'
    | '/members/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/logs'
    | '/normalize'
    | '/usage'
    | '/config/flyer'
    | '/config/ingest-keys'
    | '/config/ranking'
    | '/data/guidance'
    | '/discovery/satellites'
    | '/config'
    | '/data'
    | '/discovery'
    | '/members'
    | '/data/recipes/$slug'
    | '/data/stores/$slug'
    | '/members/$id/$section'
    | '/data/recipes'
    | '/data/stores'
    | '/members/$id'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/logs'
    | '/normalize'
    | '/usage'
    | '/config/flyer'
    | '/config/ingest-keys'
    | '/config/ranking'
    | '/data/guidance'
    | '/discovery/satellites'
    | '/config/'
    | '/data/'
    | '/discovery/'
    | '/members/'
    | '/data/recipes/$slug'
    | '/data/stores/$slug'
    | '/members/$id/$section'
    | '/data/recipes/'
    | '/data/stores/'
    | '/members/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  LogsRoute: typeof LogsRoute
  NormalizeRoute: typeof NormalizeRoute
  UsageRoute: typeof UsageRoute
  ConfigFlyerRoute: typeof ConfigFlyerRoute
  ConfigIngestKeysRoute: typeof ConfigIngestKeysRoute
  ConfigRankingRoute: typeof ConfigRankingRoute
  DataGuidanceRoute: typeof DataGuidanceRoute
  DiscoverySatellitesRoute: typeof DiscoverySatellitesRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  DataIndexRoute: typeof DataIndexRoute
  DiscoveryIndexRoute: typeof DiscoveryIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  DataRecipesSlugRoute: typeof DataRecipesSlugRoute
  DataStoresSlugRoute: typeof DataStoresSlugRoute
  MembersIdSectionRoute: typeof MembersIdSectionRoute
  DataRecipesIndexRoute: typeof DataRecipesIndexRoute
  DataStoresIndexRoute: typeof DataStoresIndexRoute
  MembersIdIndexRoute: typeof MembersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normalize': {
      id: '/normalize'
      path: '/normalize'
      fullPath: '/normalize'
      preLoaderRoute: typeof NormalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/': {
      id: '/discovery/'
      path: '/discovery'
      fullPath: '/discovery/'
      preLoaderRoute: typeof DiscoveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/satellites': {
      id: '/discovery/satellites'
      path: '/discovery/satellites'
      fullPath: '/discovery/satellites'
      preLoaderRoute: typeof DiscoverySatellitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/guidance': {
      id: '/data/guidance'
      path: '/data/guidance'
      fullPath: '/data/guidance'
      preLoaderRoute: typeof DataGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/ranking': {
      id: '/config/ranking'
      path: '/config/ranking'
      fullPath: '/config/ranking'
      preLoaderRoute: typeof ConfigRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/ingest-keys': {
      id: '/config/ingest-keys'
      path: '/config/ingest-keys'
      fullPath: '/config/ingest-keys'
      preLoaderRoute: typeof ConfigIngestKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/flyer': {
      id: '/config/flyer'
      path: '/config/flyer'
      fullPath: '/config/flyer'
      preLoaderRoute: typeof ConfigFlyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id/': {
      id: '/members/$id/'
      path: '/members/$id'
      fullPath: '/members/$id/'
      preLoaderRoute: typeof MembersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/stores/': {
      id: '/data/stores/'
      path: '/data/stores'
      fullPath: '/data/stores/'
      preLoaderRoute: typeof DataStoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/recipes/': {
      id: '/data/recipes/'
      path: '/data/recipes'
      fullPath: '/data/recipes/'
      preLoaderRoute: typeof DataRecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id/$section': {
      id: '/members/$id/$section'
      path: '/members/$id/$section'
      fullPath: '/members/$id/$section'
      preLoaderRoute: typeof MembersIdSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/stores/$slug': {
      id: '/data/stores/$slug'
      path: '/data/stores/$slug'
      fullPath: '/data/stores/$slug'
      preLoaderRoute: typeof DataStoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/recipes/$slug': {
      id: '/data/recipes/$slug'
      path: '/data/recipes/$slug'
      fullPath: '/data/recipes/$slug'
      preLoaderRoute: typeof DataRecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  LogsRoute: LogsRoute,
  NormalizeRoute: NormalizeRoute,
  UsageRoute: UsageRoute,
  ConfigFlyerRoute: ConfigFlyerRoute,
  ConfigIngestKeysRoute: ConfigIngestKeysRoute,
  ConfigRankingRoute: ConfigRankingRoute,
  DataGuidanceRoute: DataGuidanceRoute,
  DiscoverySatellitesRoute: DiscoverySatellitesRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  DataIndexRoute: DataIndexRoute,
  DiscoveryIndexRoute: DiscoveryIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  DataRecipesSlugRoute: DataRecipesSlugRoute,
  DataStoresSlugRoute: DataStoresSlugRoute,
  MembersIdSectionRoute: MembersIdSectionRoute,
  DataRecipesIndexRoute: DataRecipesIndexRoute,
  DataStoresIndexRoute: DataStoresIndexRoute,
  MembersIdIndexRoute: MembersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
