// AI-generated recipe description (derived-recipe-metadata). The `description` is the
// recipe's semantic-identity field — the embed source AND the compact "why this dish"
// row meal-plan retrieval reasons over. It is DERIVED, not authored: generated here from
// the recipe's authored FACETS (not the body — the reconcile stays pure D1 + AI), once
// at import (src/write-tools.ts, no lag) and thereafter regenerated on the cron whenever
// the facets change (a `content_hash` gate). Stored in the reconcile-owned `recipe_derived`
// table, never in frontmatter.
//
// Prompt + model are the spike's conclusion (see the change's design.md, Runs 1-3):
// mistral-small-3.1-24b, an anti-cliché one-sentence prompt with 3 few-shot exemplars, plus
// the two guardrails (low-signal → stay general, don't invent; many-ingredient → name
// the single distinctive element). Same `env.AI` binding and structured-error discipline
// as src/embedding.ts.

import type { Env } from "./env.js";
import { ToolError } from "./errors.js";
import { hashText } from "./hash.js";

/** Text-generation model for descriptions. Swappable config; the eval (task 6.1) owns the choice. */
export const DESC_MODEL = "@cf/mistralai/mistral-small-3.1-24b-instruct";

/** The authored facets a description is derived from — the describe input AND the content_hash domain. */
export interface RecipeFacets {
  title: string;
  ingredients_key: string[];
  course: string[];
  protein: string | null;
  cuisine: string | null;
  time_total: number | null;
  dietary: string[];
  season: string[];
}

/**
 * Stable hash of the authored facets a description derives from. Identical inputs → identical
 * hash across the import path (src/write-tools.ts) and the reconcile, so a description generated
 * at import is not regenerated by the next cron tick. Excludes every DERIVED field, so writing a
 * regenerated description never flips the hash (no regeneration loop).
 */
export function contentHash(f: RecipeFacets): string {
  // Array order is the canonical projected order (frontmatter order, preserved by the build and
  // the write path); a JSON tuple keeps the shape deterministic without masking a real reorder.
  return hashText(
    JSON.stringify([
      f.title,
      f.ingredients_key,
      f.course,
      f.protein,
      f.cuisine,
      f.time_total,
      f.dietary,
      f.season,
    ]),
  );
}

/**
 * Extract a recipe's facets from its (authored) frontmatter, normalized to mirror the build's
 * `recipes` projection (course lower-cased; array fields coerced) so the content_hash computed
 * at import (the synchronous seed) matches the one the reconcile later computes from the
 * projected row — avoiding a redundant regenerate on the first tick.
 */
export function facetsFromFrontmatter(fm: Record<string, unknown>): RecipeFacets {
  const arr = (v: unknown): string[] =>
    Array.isArray(v)
      ? v.filter((x): x is string => typeof x === "string")
      : typeof v === "string" && v
        ? [v]
        : [];
  return {
    title: typeof fm.title === "string" ? fm.title : "",
    ingredients_key: arr(fm.ingredients_key),
    course: arr(fm.course)
      .map((c) => c.trim().toLowerCase())
      .filter((c) => c.length > 0),
    protein: typeof fm.protein === "string" ? fm.protein : null,
    cuisine: typeof fm.cuisine === "string" ? fm.cuisine : null,
    time_total: typeof fm.time_total === "number" ? fm.time_total : null,
    dietary: arr(fm.dietary),
    season: arr(fm.season),
  };
}

/** Compact one-line render of the facets, matching the few-shot exemplar format. */
export function buildDescribeInput(f: RecipeFacets): string {
  const parts = [`${f.title} — ${f.ingredients_key.join(", ")}`];
  if (f.course.length) parts.push(`; ${f.course.join("/")}`);
  if (f.protein) parts.push(` | ${f.protein}`);
  if (f.cuisine) parts.push(` | ${f.cuisine}`);
  if (typeof f.time_total === "number") parts.push(` | ~${f.time_total} min`);
  if (f.dietary.length) parts.push(` | ${f.dietary.join(", ")}`);
  return parts.join("");
}

const SYSTEM_PROMPT = [
  "You write ONE recipe description for a home cook — the text a semantic search indexes and the one-line 'why this dish' shown in a menu, so it must capture what makes THIS dish distinct from similar recipes.",
  "Rules:",
  "- Exactly ONE sentence, 25-40 words.",
  "- Lead with the dish's defining trait: its standout flavor, texture, or technique — the specific thing that sets it apart.",
  "- Be concrete and sensory (name the ingredients/technique that matter); avoid generic praise.",
  "- BANNED unless genuinely the dish's defining trait: 'perfect for', 'cozy', 'weeknight', 'comforting', 'delicious', 'flavorful', and naming the occasion.",
  "- If the input lacks detail, stay general rather than inventing specifics; never name an ingredient that was not given.",
  "- For a many-ingredient dish, name the single most distinctive element — do not enumerate every ingredient or over-specify a technique you are unsure of.",
  "- Output only the sentence — no title, quotes, field names, or preamble.",
].join("\n");

// 3 few-shot exemplars (input in buildDescribeInput's format → target description), anchoring a
// plain, sensory, length-disciplined voice across a braise, a quick pasta, and a cold side.
const FEW_SHOT: Array<{ input: string; output: string }> = [
  {
    input: "Beef Bourguignon — beef chuck, red wine, bacon, pearl onions, mushrooms, thyme; main | beef | french | ~180 min",
    output:
      "Beef chuck turns meltingly tender in a red-wine braise with smoky bacon, sweet pearl onions, and mushrooms, the sauce cooked down to a deep, glossy richness.",
  },
  {
    input: "Cacio e Pepe — spaghetti, pecorino, black pepper; main | italian | ~15 min",
    output:
      "Pecorino and cracked black pepper emulsify with starchy pasta water into a silky, sharp, peppery sauce that clings to every strand of spaghetti.",
  },
  {
    input: "Smashed Cucumber Salad — cucumber, garlic, soy sauce, black vinegar, chili oil, sesame; side | chinese | ~10 min | vegan",
    output:
      "Craggy smashed cucumbers soak up a garlicky soy-and-black-vinegar dressing slicked with chili oil, staying ice-cold and crunchy under a nutty sesame finish.",
  },
];

/** Workers AI instruct/chat response: `{ response: string }`. */
interface TextGenResponse {
  response?: unknown;
}

/**
 * Generate one recipe description from its authored facets via Workers AI. Maps any AI failure
 * (or an unexpectedly-shaped response) to a structured `storage_error` ToolError — never a raw
 * throw — matching the tool-boundary discipline, exactly like src/embedding.ts. Strips wrapping
 * quotes/whitespace some models emit.
 */
export async function generateDescription(env: Env, facets: RecipeFacets): Promise<string> {
  const messages = [
    { role: "system", content: SYSTEM_PROMPT },
    ...FEW_SHOT.flatMap((ex) => [
      { role: "user", content: ex.input },
      { role: "assistant", content: ex.output },
    ]),
    { role: "user", content: buildDescribeInput(facets) },
  ];

  let res: TextGenResponse;
  try {
    res = (await env.AI.run(DESC_MODEL, {
      messages,
      max_tokens: 90,
      temperature: 0.3,
    })) as unknown as TextGenResponse;
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    throw new ToolError("storage_error", `Workers AI description generation failed: ${message}`, {
      model: DESC_MODEL,
    });
  }

  const text = typeof res?.response === "string" ? res.response : "";
  const cleaned = text.trim().replace(/^["']|["']$/g, "").trim();
  if (!cleaned) {
    throw new ToolError("storage_error", "Workers AI returned an empty description", { model: DESC_MODEL });
  }
  return cleaned;
}
